# Generated by Django 2.2.5 on 2019-09-27 23:52

import buy_ticket.helpers.status_transaction
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_show', models.DateField()),
                ('is_active', models.BooleanField(verbose_name='Show Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qtd_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ticket Válido')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_ticket.Show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_ticket.Theater'),
        ),
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(buy_ticket.helpers.status_transaction.StatusTransaction('authorized_pending_capture'), 'authorized_pending_capture'), (buy_ticket.helpers.status_transaction.StatusTransaction('not_authorized'), 'not_authorized'), (buy_ticket.helpers.status_transaction.StatusTransaction('captured'), 'captured'), (buy_ticket.helpers.status_transaction.StatusTransaction('partial_capture'), 'partial_capture'), (buy_ticket.helpers.status_transaction.StatusTransaction('waiting_capture'), 'waiting_capture'), (buy_ticket.helpers.status_transaction.StatusTransaction('refunded'), 'refunded'), (buy_ticket.helpers.status_transaction.StatusTransaction('voided'), 'voided'), (buy_ticket.helpers.status_transaction.StatusTransaction('partial_refunded'), 'partial_refunded'), (buy_ticket.helpers.status_transaction.StatusTransaction('partial_void'), 'partial_void'), (buy_ticket.helpers.status_transaction.StatusTransaction('error_on_voiding'), 'error_on_voiding'), (buy_ticket.helpers.status_transaction.StatusTransaction('error_on_refunding'), 'error_on_refunding'), (buy_ticket.helpers.status_transaction.StatusTransaction('waiting_cancellation'), 'waiting_cancellation'), (buy_ticket.helpers.status_transaction.StatusTransaction('with_error'), 'with_error'), (buy_ticket.helpers.status_transaction.StatusTransaction('failed'), 'failed')], max_length=5)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_ticket.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_ticket.User')),
            ],
        ),
    ]
