# Generated by Django 2.2.5 on 2019-09-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0002_auto_20190928_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyticket',
            name='state',
            field=models.CharField(choices=[('APC', 'authorized_pending_capture'), ('NA', 'not_authorized'), ('CA', 'captured'), ('PC', 'partial_capture'), ('WCP', 'waiting_capture'), ('RE', 'refunded'), ('VO', 'voided'), ('PR', 'partial_refunded'), ('PV', 'partial_void'), ('EOV', 'error_on_voiding'), ('EOR', 'error_on_refunding'), ('WCN', 'waiting_cancellation'), ('WE', 'with_error'), ('FA', 'failed')], max_length=5),
        ),
        migrations.AlterField(
            model_name='buyticket',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_ticket.Ticket'),
        ),
    ]
