# Generated by Django 2.2.5 on 2019-09-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0005_auto_20190928_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='Ticket Comprado'),
        ),
        migrations.AlterField(
            model_name='buyticket',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ticket', to='buy_ticket.Ticket'),
        ),
    ]
