# Generated by Django 2.2.5 on 2019-09-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0006_auto_20190928_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='buy_ticket.Theater'),
        ),
    ]
